spring.application.name=userservice
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/user_db
spring.datasource.username=root
spring.datasource.password=Echo@2010
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081

